x-environment:
  &x-environment
  INITIAL: "${INITIAL:-0}"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD:
      POSTGRES_DB: cooking-blog
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432

  backend:
    build:
      context: .
    command: sh -c 'while true; do /venv/bin/python ./manage.py runserver 0.0.0.0:8000; sleep 1; done'
    #command: sleep infinity
    environment:
      <<: *x-environment
      ALLOWED_HOSTS: >-
        localhost
      DATABASE_URL: postgresql://postgres@db/cooking-blog
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - venv:/venv
      - .:/code
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  pgdata:
  venv:
  home:
